{% set name = "xpublish-wms" %}
{% set version = "0.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xpublish_wms-{{ version }}.tar.gz
  sha256: a52cdc1083b364c5da69a5e58b6dfec967b8f9b5ac877386fb6e3db735cafd92

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - cartopy
    - cf_xarray
    - mercantile
    - matplotlib-base
    - pillow
    - pykdtree
    - xarray
    - xpublish >=0.4.0
    - datashader

test:
  imports:
    - xpublish_wms
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/xpublish-community/xpublish-wms
  summary: WMS plugin for xpublish
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - abkfenris
    - mpiannucci
