{% set name = "xpublish-wms" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xpublish_wms-{{ version }}.tar.gz
  sha256: 4c6b4390ac943717cdcba9fb76f6fc9e4278a5bef4ec7b2c4ce17d8afc74d622

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - setuptools >=61
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - cartopy
    - cf_xarray
    - mercantile
    - matplotlib-base
    - pillow
    - pykdtree
    - xarray
    - xpublish <0.4.0,>=0.3.0
    - datashader

test:
  imports:
    - xpublish_wms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xpublish-community/xpublish-wms
  summary: WMS plugin for xpublish
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - abkfenris
    - mpiannucci
